name: quiz_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.5.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  audioplayers: ^6.5.1
  shared_preferences: ^2.2.2
  http: ^1.2.1          # ← THÊM DÒNG NÀY (BẮT BUỘC CHO QUIZ ONLINE)
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/cau_hoi.json
    - assets/am_thanh/dung.mp3
    - assets/am_thanh/sai.mp3
